# 服务端口
server:
  port: 8201
  # 服务名
spring:
  application:
    name: service-hosp
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: 8023love
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #rabbitmq地址
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  #mongodb地址
  data:
    mongodb:
      host: 47.105.138.124
      port: 27017
      database: yygh_hosp
  #设置sentinel地址
#  cloud:
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858
#    # nacos服务地址
    nacos:
      discovery:
        server-addr: localhost:8848

#配置mapper xml文件的路径
#mybatis-plus.mapper-locations=classpath:com/atguigu/yygh/mapper/xml/*.xml
mybatis-plus:
  mapper-locations: classpath:com/syt/yygh/mapper/xml/*.xml

  #开启sentinel
#feign:
#  sentinel:
#    enabled: true

