# 服务端口
server:
  port: 8203
  # 服务名
spring:
  application:
    name: service-user
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3306/yygh_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: 8023love
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #rabbitmq地址
  #  rabbitmq:
  #    host: 127.0.0.1
  #    port: 5672
  #    username: guest
  #    password: guest
  #设置sentinel地址
  cloud:
    #    sentinel:
    #      transport:
    #        dashboard: http://127.0.0.1:8858
    #    # nacos服务地址
    nacos:
      discovery:
        server-addr: 192.168.0.105:8848
  redis:
    host: 192.168.0.105
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0

#配置mapper xml文件的路径
#mybatis-plus.mapper-locations=classpath:com/atguigu/yygh/mapper/xml/*.xml
mybatis-plus:
  mapper-locations: classpath:com/syt/yygh/mapper/xml/*.xml

  #开启sentinel
#feign:
#  sentinel:
#    enabled: true

