server:
  port: 8204

spring:
  application:
    name: service-sms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.0.105
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.105:8848
aliyun:
  sms:
    regionId: default
    accessKeyId: default
    secret: default
  oss:
    endpoint: default
    accessKeyId: default
    secret: default
    bucket: default


