server:
  port: 80
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.106:8848
    gateway:
      discovery:
        locator:
          enabled: true  # 使用服务发现路由
      routes:
        - id: servie_hosp  #路由id
          uri: lb://service-hosp  #路由url
          predicates: Path=/*/hosp/**  #设置路由断言，代理serviceId为auth-service的/auth/路径
        - id: servie_cmn
          uri: lb://service-cmn
          predicates: Path=/*/cmn/**

